<?php

return [
    'permissions' => [
        ['name' => 'dashboard.view', 'label' => 'Xem bảng điều khiển', 'module' => 'Bảng điều khiển'],
        ['name' => 'media.manage', 'label' => 'Quản lý thư viện media', 'module' => 'Media'],
        ['name' => 'products.manage', 'label' => 'Quản lý sản phẩm', 'module' => 'Sản phẩm'],
        ['name' => 'products.view', 'label' => 'Xem sản phẩm', 'module' => 'Sản phẩm'],
        ['name' => 'products.create', 'label' => 'Thêm sản phẩm', 'module' => 'Sản phẩm'],
        ['name' => 'products.update', 'label' => 'Sửa sản phẩm', 'module' => 'Sản phẩm'],
        ['name' => 'products.delete', 'label' => 'Xóa sản phẩm', 'module' => 'Sản phẩm'],
        ['name' => 'posts.manage', 'label' => 'Quản lý tin tức', 'module' => 'Tin tức'],
        ['name' => 'posts.view', 'label' => 'Xem tin tức', 'module' => 'Tin tức'],
        ['name' => 'posts.create', 'label' => 'Thêm tin tức', 'module' => 'Tin tức'],
        ['name' => 'posts.update', 'label' => 'Sửa tin tức', 'module' => 'Tin tức'],
        ['name' => 'posts.delete', 'label' => 'Xóa tin tức', 'module' => 'Tin tức'],
        ['name' => 'pages.manage', 'label' => 'Quản lý trang giới thiệu', 'module' => 'Giới thiệu'],
        ['name' => 'pages.view', 'label' => 'Xem trang giới thiệu', 'module' => 'Giới thiệu'],
        ['name' => 'pages.create', 'label' => 'Thêm trang giới thiệu', 'module' => 'Giới thiệu'],
        ['name' => 'pages.update', 'label' => 'Sửa trang giới thiệu', 'module' => 'Giới thiệu'],
        ['name' => 'pages.delete', 'label' => 'Xóa trang giới thiệu', 'module' => 'Giới thiệu'],
        ['name' => 'recipes.manage', 'label' => 'Quản lý Recipes', 'module' => 'Recipes'],
        ['name' => 'recipes.view', 'label' => 'Xem Recipes', 'module' => 'Recipes'],
        ['name' => 'recipes.create', 'label' => 'Thêm Recipes', 'module' => 'Recipes'],
        ['name' => 'recipes.update', 'label' => 'Sửa Recipes', 'module' => 'Recipes'],
        ['name' => 'recipes.delete', 'label' => 'Xóa Recipes', 'module' => 'Recipes'],
        ['name' => 'investor-documents.manage', 'label' => 'Quản lý quan hệ cổ đông', 'module' => 'Quan hệ cổ đông'],
        ['name' => 'investor-documents.view', 'label' => 'Xem tài liệu cổ đông', 'module' => 'Quan hệ cổ đông'],
        ['name' => 'investor-documents.create', 'label' => 'Thêm tài liệu cổ đông', 'module' => 'Quan hệ cổ đông'],
        ['name' => 'investor-documents.update', 'label' => 'Sửa tài liệu cổ đông', 'module' => 'Quan hệ cổ đông'],
        ['name' => 'investor-documents.delete', 'label' => 'Xóa tài liệu cổ đông', 'module' => 'Quan hệ cổ đông'],
        ['name' => 'recruitment.manage', 'label' => 'Quản lý tuyển dụng', 'module' => 'Tuyển dụng'],
        ['name' => 'recruitment.view', 'label' => 'Xem tuyển dụng', 'module' => 'Tuyển dụng'],
        ['name' => 'recruitment.create', 'label' => 'Thêm tuyển dụng', 'module' => 'Tuyển dụng'],
        ['name' => 'recruitment.update', 'label' => 'Sửa tuyển dụng', 'module' => 'Tuyển dụng'],
        ['name' => 'recruitment.delete', 'label' => 'Xóa tuyển dụng', 'module' => 'Tuyển dụng'],
        ['name' => 'contacts.manage', 'label' => 'Quản lý liên hệ', 'module' => 'Liên hệ'],
        ['name' => 'settings.manage', 'label' => 'Quản lý cấu hình hệ thống', 'module' => 'Hệ thống'],
        ['name' => 'users.view', 'label' => 'Xem quản trị viên', 'module' => 'Quản trị viên'],
        ['name' => 'users.create', 'label' => 'Thêm quản trị viên', 'module' => 'Quản trị viên'],
        ['name' => 'users.update', 'label' => 'Sửa và gán vai trò', 'module' => 'Quản trị viên'],
        ['name' => 'users.delete', 'label' => 'Xóa quản trị viên', 'module' => 'Quản trị viên'],
        ['name' => 'roles.view', 'label' => 'Xem vai trò', 'module' => 'Vai trò'],
        ['name' => 'roles.create', 'label' => 'Thêm vai trò', 'module' => 'Vai trò'],
        ['name' => 'roles.update', 'label' => 'Sửa và gán quyền cho vai trò', 'module' => 'Vai trò'],
        ['name' => 'roles.delete', 'label' => 'Xóa vai trò', 'module' => 'Vai trò'],
        ['name' => 'permissions.view', 'label' => 'Xem quyền hạn', 'module' => 'Quyền hạn'],
        ['name' => 'activity.view', 'label' => 'Xem nhật ký hoạt động', 'module' => 'Nhật ký hoạt động'],
    ],
];
