<div>
    <x-admin.page-header title="Quản lý tin tiêu điểm" description="Chọn tối đa {{ $limit }} bài viết nổi bật cho trang chủ." :breadcrumbs="$breadcrumbs" />
    <section class="card featured-section"><div class="featured-heading"><div><h2>Tin đang nổi bật</h2><p>{{ $featured->count() }} / {{ $limit }} vị trí đã dùng</p></div><div><button class="button button-secondary" wire:click="updateOrder">Cập nhật thứ tự</button><button class="button button-danger" wire:click="removeFeatured" @disabled(!$featuredSelected)>Bỏ các tin đã chọn</button></div></div>
        @if($featured->isEmpty())<x-ui.empty-state title="Chưa có tin tiêu điểm" description="Chọn bài viết từ danh sách bên dưới." icon="newspaper" />@else<div class="table-responsive"><table class="data-table"><thead><tr><th></th><th>Thứ tự</th><th>Hình</th><th>Tiêu đề</th><th>Chuyên mục</th></tr></thead><tbody>@foreach($featured as $item)<tr><td><input class="table-checkbox" type="checkbox" wire:model.live="featuredSelected" value="{{ $item->id }}"></td><td><input class="input order-input" type="number" wire:model="sortOrders.{{ $item->id }}"></td><td><div class="product-thumb">@if($item->featuredMedia)<img src="{{ $item->featuredMedia->url }}" alt="">@else<x-ui.icon name="image" />@endif</div></td><td><strong>{{ $item->getTranslation('title', $locale, false) }}</strong></td><td>{{ $item->category?->getTranslation('name', $locale, false) }}</td></tr>@endforeach</tbody></table></div>@endif
    </section>
    <section class="card filter-card featured-search"><div class="featured-heading"><div><h2>Danh sách tin tức</h2><p>Chọn tin để đưa lên vị trí tiêu điểm.</p></div></div><div class="category-filter-grid"><x-form.input name="search" label="Từ khóa" wire:model.live.debounce.350ms="search" /><div class="form-field"><label>Chuyên mục</label><select class="select" wire:model.live="category"><option value="">Tất cả</option>@foreach($categories as $cat)<option value="{{ $cat->id }}">{{ $cat->getTranslation('name', $locale, false) }}</option>@endforeach</select></div><button class="button button-primary" wire:click="addFeatured" @disabled(!$selected || $featured->count() >= $limit)>Xét tiêu điểm các tin đã chọn</button></div>
        <div class="table-responsive"><table class="data-table"><thead><tr><th></th><th>Hình</th><th>Tiêu đề</th><th>Chuyên mục</th></tr></thead><tbody>@foreach($available as $item)<tr><td><input class="table-checkbox" type="checkbox" wire:model.live="selected" value="{{ $item->id }}"></td><td><div class="product-thumb">@if($item->featuredMedia)<img src="{{ $item->featuredMedia->url }}" alt="">@else<x-ui.icon name="image" />@endif</div></td><td>{{ $item->getTranslation('title', $locale, false) }}</td><td>{{ $item->category?->getTranslation('name', $locale, false) }}</td></tr>@endforeach</tbody></table></div><x-ui.pagination :paginator="$available" />
    </section>
</div>
