<div>
    <x-admin.page-header :title="$post ? 'Cập nhật tin tức' : 'Thêm tin tức'" description="Biên tập nội dung, lịch xuất bản và SEO cho Việt, Anh, Trung." :breadcrumbs="$breadcrumbs">
        <x-slot:actions><a class="button button-secondary" href="{{ route('admin.news.posts.index') }}" wire:navigate>Quay lại</a>@if($post)<a class="button button-ghost" href="{{ route('admin.news.posts.preview', $post) }}" target="_blank"><x-ui.icon name="eye" size="18" /> Xem trước</a>@endif<x-ui.button type="submit" form="post-form" icon="save">Lưu bài viết</x-ui.button></x-slot:actions>
    </x-admin.page-header>
    <form id="post-form" wire:submit="save" data-dirty-form><div class="product-form-grid">
        <aside><x-form.section title="Thông tin chung" description="Áp dụng cho cả ba ngôn ngữ" icon="info"><div class="form-stack">
            <div class="form-field"><label>Chuyên mục <span>*</span></label><select class="select" wire:model="post_category_id"><option value="">Chọn chuyên mục</option>@foreach($categories as $cat)<option value="{{ $cat->id }}">{{ $cat->getTranslation('name', 'vi', false) }}</option>@endforeach</select><x-form.field-error name="post_category_id" /></div>
            <x-form.input name="code" label="Mã quản trị" wire:model="code" />
            <div class="form-field"><label>Ảnh đại diện <span>*</span></label>@if($featured_image)<div class="media-preview news-media-preview has-image"><img src="{{ $featured_image->temporaryUrl() }}" alt=""></div>@elseif($post?->featuredMedia && !$remove_image)<div class="media-preview news-media-preview has-image"><img src="{{ $post->featuredMedia->url }}" alt=""></div>@else<div class="media-preview news-media-preview"><span class="media-placeholder"><x-ui.icon name="image" size="30" /> Ảnh đề nghị 1200 × 675</span></div>@endif<input class="input" type="file" wire:model="featured_image" accept=".jpg,.jpeg,.png,.webp">@if($featured_image || ($post?->featuredMedia && !$remove_image))<button class="button button-ghost" type="button" wire:click="removeFeaturedImage">Xóa ảnh</button>@endif<x-form.field-error name="featured_image" /></div>
            <x-form.input name="sort_order" label="Thứ tự hiển thị" type="number" wire:model="sort_order" min="0" />
            <div class="switch-group"><x-form.switch name="is_featured" label="Tin tiêu điểm" wire:model="is_featured" /><x-form.switch name="is_active" label="Đang hiển thị" wire:model="is_active" /></div>
        </div></x-form.section></aside>
        <div><x-form.language-tabs :locales="$locales">@foreach($locales as $locale => $label)<section id="panel-{{ $locale }}" class="tab-panel" x-show="active === '{{ $locale }}'" x-cloak>
            <x-form.section title="Nội dung {{ $label }}" description="Bản dịch và lịch xuất bản độc lập" icon="languages"><div class="localized-fields">
                <x-form.input name="title[{{ $locale }}]" label="Tiêu đề" wire:model.blur="title.{{ $locale }}" :required="$locale === 'vi'" />
                <div class="form-field"><label>Friendly URL</label><div class="slug-input"><span>/{{ $locale }}/news/</span><input class="input" wire:model="slug.{{ $locale }}"><button type="button" wire:click="generateSlug('{{ $locale }}')">Tạo lại</button></div><x-form.field-error name="slug.{{ $locale }}" /></div>
                <x-form.textarea name="excerpt[{{ $locale }}]" label="Mô tả ngắn" wire:model="excerpt.{{ $locale }}" rows="4" maxlength="2000" />
                <div class="form-field rich-editor"><label>Nội dung tin</label><textarea id="post-content-{{ $locale }}" class="textarea rich-text-textarea" rows="14" wire:model="content.{{ $locale }}"></textarea><x-form.field-error name="content.{{ $locale }}" /></div>
                <details class="seo-panel" open><summary>Search Engine Optimization (SEO)</summary><div class="seo-grid"><x-form.input name="seo_title[{{ $locale }}]" label="Tiêu đề SEO" wire:model="seo_title.{{ $locale }}" maxlength="255" /><x-form.textarea name="meta_description[{{ $locale }}]" label="Meta description" wire:model="meta_description.{{ $locale }}" rows="3" maxlength="500" /><x-form.input name="og_title[{{ $locale }}]" label="Tiêu đề chia sẻ mạng xã hội" wire:model="og_title.{{ $locale }}" /><x-form.textarea name="og_description[{{ $locale }}]" label="Mô tả chia sẻ" wire:model="og_description.{{ $locale }}" rows="2" /></div></details>
                <div class="publication-grid"><x-form.select name="translation_status[{{ $locale }}]" label="Trạng thái bản dịch" :options="$statuses" wire:model.live="translation_status.{{ $locale }}" />@if(($translation_status[$locale] ?? '') === 'scheduled')<x-form.input name="locale_published_at[{{ $locale }}]" label="Ngày xuất bản" type="datetime-local" wire:model="locale_published_at.{{ $locale }}" required />@endif</div>
            </div></x-form.section>
        </section>@endforeach</x-form.language-tabs></div>
    </div></form>
</div>
