<div class="access-page">
    <x-admin.page-header title="Nhật ký hoạt động" description="Theo dõi đầy đủ thao tác của quản trị viên trên toàn bộ CMS" :breadcrumbs="$breadcrumbs" />
    <section class="audit-overview card"><div><span class="audit-live-dot"></span><strong>Đang ghi nhận hoạt động</strong><small>Mỗi thao tác được lưu kèm thời gian, IP, trình duyệt và đối tượng liên quan.</small></div><span><x-ui.icon name="shield" size="18" /> Nhật ký chỉ đọc</span></section>
    <section class="filter-card card"><div class="audit-filter-grid">
        <div class="filter-search"><label for="audit-search">Nội dung</label><div><x-ui.icon name="search" size="18" /><input id="audit-search" class="input" wire:model.live.debounce.300ms="search" placeholder="Tìm theo mô tả hoạt động"></div></div>
        <div><label for="audit-admin">Quản trị viên</label><select id="audit-admin" class="select" wire:model.live="adminId"><option value="">Tất cả quản trị viên</option>@foreach($admins as $admin)<option value="{{ $admin->id }}">{{ $admin->name }} ({{ '@'.$admin->username }})</option>@endforeach</select></div>
        <div><label for="audit-action">Hành động</label><select id="audit-action" class="select" wire:model.live="action"><option value="">Tất cả hành động</option>@foreach($actions as $actionName)<option value="{{ $actionName }}">{{ ['created'=>'Tạo mới','updated'=>'Cập nhật','deleted'=>'Xóa','login'=>'Đăng nhập','logout'=>'Đăng xuất','roles_assigned'=>'Gán vai trò','permissions_assigned'=>'Gán quyền'][$actionName] ?? $actionName }}</option>@endforeach</select></div>
        <div><label for="audit-module">Module</label><select id="audit-module" class="select" wire:model.live="module"><option value="">Tất cả module</option>@foreach($modules as $moduleName)<option>{{ $moduleName }}</option>@endforeach</select></div>
        <div><label for="audit-from">Từ ngày</label><input id="audit-from" class="input" type="date" wire:model.live="dateFrom"></div><div><label for="audit-to">Đến ngày</label><input id="audit-to" class="input" type="date" wire:model.live="dateTo"></div>
        <button class="button button-ghost" wire:click="resetFilters">Đặt lại</button>
    </div></section>
    <section class="card access-list-card">@if($logs->isEmpty())<x-ui.empty-state title="Chưa có hoạt động phù hợp" description="Nhật ký mới sẽ xuất hiện tại đây khi quản trị viên thao tác." />@else<div class="table-responsive"><table class="data-table audit-table"><thead><tr><th>Thời gian</th><th>Quản trị viên</th><th>Hành động</th><th>Module</th><th>Địa chỉ IP</th><th class="table-actions-heading">Chi tiết</th></tr></thead><tbody>
        @foreach($logs as $log)@php $props=$log->properties; $actionLabel=['created'=>'Tạo mới','updated'=>'Cập nhật','deleted'=>'Xóa','login'=>'Đăng nhập','logout'=>'Đăng xuất','roles_assigned'=>'Gán vai trò','permissions_assigned'=>'Gán quyền'][$log->event] ?? $log->event; $tone=['created'=>'success','updated'=>'info','deleted'=>'warning','login'=>'success','logout'=>'neutral'][$log->event] ?? 'info'; @endphp
        <tr wire:key="audit-{{ $log->id }}"><td><time datetime="{{ $log->created_at->toIso8601String() }}"><strong>{{ $log->created_at->format('H:i:s') }}</strong><small>{{ $log->created_at->format('d/m/Y') }}</small></time></td><td><div class="audit-actor"><span>{{ mb_strtoupper(mb_substr($log->causer?->name ?? $props->get('actor_name','?'),0,1)) }}</span><div><strong>{{ $log->causer?->name ?? $props->get('actor_name','Tài khoản đã xóa') }}</strong><small>{{ $log->causer?->username ? '@'.$log->causer->username : '' }}</small></div></div></td><td><x-ui.badge :tone="$tone">{{ $actionLabel }}</x-ui.badge><p>{{ $log->description }}</p></td><td><span class="access-chip">{{ $props->get('module','—') }}</span></td><td><code>{{ $props->get('ip_address','—') }}</code></td><td><div class="row-actions"><button class="icon-button" wire:click="view({{ $log->id }})" title="Xem chi tiết"><x-ui.icon name="eye" size="18" /></button></div></td></tr>
        @endforeach</tbody></table></div><x-ui.pagination :paginator="$logs" :per-page-options="[10,20,50,100]" />@endif</section>
    @if($viewingLog)@php $props=$viewingLog->properties; @endphp<div class="access-modal audit-detail-modal" x-data x-on:keydown.escape.window="$wire.closeDetail()"><button class="access-modal-backdrop" wire:click="closeDetail"></button><section class="access-modal-panel"><header><div><span>Chi tiết sự kiện #{{ $viewingLog->id }}</span><h2>{{ $viewingLog->description }}</h2></div><button class="icon-button" wire:click="closeDetail"><x-ui.icon name="x" /></button></header><div class="access-modal-body">
        <div class="audit-detail-highlight"><span><x-ui.icon name="history" size="24" /></span><div><strong>{{ $viewingLog->created_at->format('H:i:s, d/m/Y') }}</strong><small>{{ $viewingLog->created_at->diffForHumans() }}</small></div></div>
        <dl class="audit-detail-grid"><div><dt>Quản trị viên</dt><dd>{{ $viewingLog->causer?->name ?? $props->get('actor_name','Tài khoản đã xóa') }}</dd></div><div><dt>Hành động</dt><dd>{{ $viewingLog->event }}</dd></div><div><dt>Module</dt><dd>{{ $props->get('module','—') }}</dd></div><div><dt>Đối tượng</dt><dd>{{ $props->get('subject_label', $viewingLog->subject ? '#'.$viewingLog->subject_id : '—') }}</dd></div><div><dt>Địa chỉ IP</dt><dd><code>{{ $props->get('ip_address','—') }}</code></dd></div><div><dt>Phương thức</dt><dd>{{ $props->get('method','—') }}</dd></div><div class="is-wide"><dt>Trình duyệt / Thiết bị</dt><dd>{{ $props->get('user_agent','Không xác định') }}</dd></div>@if($props->get('fields_changed'))<div class="is-wide"><dt>Trường đã thay đổi</dt><dd><div class="chip-list">@foreach($props->get('fields_changed') as $field)<code>{{ $field }}</code>@endforeach</div></dd></div>@endif</dl>
    </div><footer><button class="button button-secondary" wire:click="closeDetail">Đóng</button></footer></section></div>@endif
</div>
