<div class="access-page">
    <x-admin.page-header title="Quản lý quyền hạn" description="Danh mục các khả năng có thể cấp cho từng vai trò quản trị" :breadcrumbs="$breadcrumbs">
        <x-slot:actions>@can('permissions.create')<button class="button button-primary" wire:click="create"><x-ui.icon name="plus" size="18" /> Thêm quyền</button>@endcan</x-slot:actions>
    </x-admin.page-header>
    <section class="access-intro card"><span><x-ui.icon name="info" size="24" /></span><div><strong>Quyền hệ thống và quyền tùy chỉnh</strong><p>Quyền hệ thống gắn với chức năng cốt lõi nên không thể xóa. Bạn vẫn có thể cập nhật tên hiển thị và mô tả.</p></div><a href="{{ route('admin.access.roles') }}" wire:navigate>Gán quyền cho vai trò <x-ui.icon name="chevron-right" size="16" /></a></section>
    <section class="filter-card card"><div class="permission-filter-grid"><div class="filter-search"><label for="permission-search">Tìm kiếm</label><div><x-ui.icon name="search" size="18" /><input id="permission-search" class="input" wire:model.live.debounce.300ms="search" placeholder="Tên, mã hoặc mô tả quyền"></div></div><div><label for="permission-module">Module</label><select id="permission-module" class="select" wire:model.live="moduleFilter"><option value="">Tất cả module</option>@foreach($modules as $moduleName)<option>{{ $moduleName }}</option>@endforeach</select></div><button class="button button-ghost" wire:click="resetFilters">Đặt lại</button></div></section>
    <section class="card access-list-card">@if($permissions->isEmpty())<x-ui.empty-state title="Không tìm thấy quyền hạn" description="Hãy thay đổi bộ lọc hoặc thêm quyền tùy chỉnh." />@else<div class="table-responsive"><table class="data-table permission-table"><thead><tr><th>Quyền hạn</th><th>Module</th><th>Loại</th><th>Vai trò sử dụng</th><th class="table-actions-heading">Thao tác</th></tr></thead><tbody>
        @foreach($permissions as $permission)<tr wire:key="permission-{{ $permission->id }}"><td><div class="permission-name"><strong>{{ $permission->display_name ?: $permission->name }}</strong><code>{{ $permission->name }}</code>@if($permission->description)<small>{{ $permission->description }}</small>@endif</div></td><td><span class="access-chip">{{ $permission->module ?: 'Khác' }}</span></td><td><x-ui.badge :tone="$permission->is_system ? 'info' : 'neutral'">{{ $permission->is_system ? 'Hệ thống' : 'Tùy chỉnh' }}</x-ui.badge></td><td><strong>{{ $permission->roles_count }}</strong> vai trò</td><td><div class="row-actions">@can('permissions.update')<button class="icon-button is-success" wire:click="edit({{ $permission->id }})" title="Chỉnh sửa"><x-ui.icon name="edit" size="17" /></button>@endcan @can('permissions.delete')@if(!$permission->is_system && $permission->roles_count === 0)<button class="icon-button is-danger" wire:click="requestDelete({{ $permission->id }})" title="Xóa"><x-ui.icon name="trash" size="17" /></button>@endif @endcan</div></td></tr>@endforeach
    </tbody></table></div><x-ui.pagination :paginator="$permissions" />@endif</section>
    @if($showForm)<div class="access-modal" x-data x-on:keydown.escape.window="$wire.closeForm()"><button class="access-modal-backdrop" wire:click="closeForm"></button><section class="access-modal-panel permission-form-panel" role="dialog" aria-modal="true"><header><div><span>Danh mục quyền hạn</span><h2>{{ $editingId ? 'Chỉnh sửa quyền' : 'Thêm quyền mới' }}</h2></div><button class="icon-button" wire:click="closeForm"><x-ui.icon name="x" /></button></header><form wire:submit="save"><div class="access-modal-body access-form-grid">
        <div class="form-field"><label for="permission-name">Mã quyền <span>*</span></label><input id="permission-name" class="input" wire:model="name" {{ $editingId && \App\Models\Permission::find($editingId)?->is_system ? 'disabled' : '' }}><p class="field-help">Ví dụ: reports.export</p>@error('name')<p class="field-error">{{ $message }}</p>@enderror</div>
        <div class="form-field"><label for="permission-label">Tên hiển thị <span>*</span></label><input id="permission-label" class="input" wire:model="display_name">@error('display_name')<p class="field-error">{{ $message }}</p>@enderror</div>
        <div class="form-field is-wide"><label for="permission-module-input">Module <span>*</span></label><input id="permission-module-input" class="input" wire:model="module" list="permission-modules"><datalist id="permission-modules">@foreach($modules as $moduleName)<option value="{{ $moduleName }}">@endforeach</datalist>@error('module')<p class="field-error">{{ $message }}</p>@enderror</div>
        <div class="form-field is-wide"><label for="permission-description">Mô tả</label><textarea id="permission-description" class="textarea" wire:model="description" placeholder="Giải thích phạm vi và thao tác mà quyền này cho phép"></textarea>@error('description')<p class="field-error">{{ $message }}</p>@enderror</div>
    </div><footer><button class="button button-secondary" type="button" wire:click="closeForm">Hủy</button><button class="button button-primary" type="submit"><x-ui.icon name="save" size="17" /> Lưu quyền</button></footer></form></section></div>@endif
    @if($pendingDeleteId)<div class="modal-backdrop" wire:click.self="cancelDelete"><section class="modal-card"><div class="modal-icon"><x-ui.icon name="alert" size="30" /></div><h2>Xóa quyền hạn?</h2><p>Quyền <strong>“{{ $pendingDeleteName }}”</strong> sẽ bị xóa vĩnh viễn.</p><div class="modal-actions"><button class="button button-secondary" wire:click="cancelDelete">Hủy</button><button class="button button-danger" wire:click="confirmDelete">Xóa quyền</button></div></section></div>@endif
</div>
