const vi = {
  common: { loading: 'Đang tải...', retry: 'Thử lại', viewAll: 'Xem tất cả', readMore: 'Đọc thêm', download: 'Tải xuống', search: 'Tìm kiếm', close: 'Đóng', backHome: 'Về trang chủ', noContent: 'Nội dung đang được cập nhật.', minutes: '{{count}} phút' },
  language: { label: 'Ngôn ngữ', vi: 'VI', en: 'EN', 'zh-CN': '中文' },
  actions: { all: 'Tất cả', viewDetails: 'Xem chi tiết', requestAdvice: 'Yêu cầu tư vấn', continueProducts: 'Tiếp tục xem sản phẩm', submitAnotherInquiry: 'Gửi yêu cầu khác', sending: 'Đang gửi...', submitContact: 'Gửi liên hệ', submitCv: 'Gửi CV ứng tuyển', submitAnotherApplication: 'Gửi hồ sơ khác', submitApplication: 'Gửi ứng tuyển', exploreIdi: 'Khám phá IDI', exploreProducts: 'Khám phá sản phẩm', learnMore: 'Tìm hiểu thêm →', viewCatalog: 'Xem toàn bộ danh mục →', customProduction: 'Nhận sản xuất theo quy cách riêng', featuredRead: 'Đọc bài nổi bật', clearFilters: 'Xóa bộ lọc', allNews: 'Xem tất cả tin tức', previous: 'Trước', next: 'Sau', printArticle: 'In bài viết', viewMore: 'Xem thêm', retryLoad: 'Thử tải lại' },
  nav: { main: 'Điều hướng chính', footer: 'Điều hướng cuối trang', openMenu: 'Mở menu', closeMenu: 'Đóng menu', home: 'Trang chủ', about: 'Về IDI', story: 'Lịch sử phát triển', values: 'Giá trị cốt lõi', products: 'Sản phẩm', sustainability: 'Phát triển bền vững', investors: 'Nhà đầu tư', overview: 'Tổng quan', announcements: 'Thông báo', financials: 'Báo cáo tài chính', annualReports: 'Báo cáo thường niên', agm: 'Đại hội cổ đông', greenBond: 'Trái phiếu', news: 'Tin tức', recipes: 'Món ăn', careers: 'Tuyển dụng', contact: 'Liên hệ', requestQuote: 'Yêu cầu báo giá', investorMenu: 'Danh mục nhà đầu tư', irContact: 'Liên hệ IR' },
  productNav: { fillet: 'Cá tra phi lê', filletDescription: 'Không da, có da và nhiều quy cách chỉnh hình', portions: 'Cá tra cắt khúc', portionsDescription: 'Cắt theo khẩu phần cho dịch vụ thực phẩm', whole: 'Cá nguyên con', wholeDescription: 'Dạng bướm, HGT và làm sạch', valueAdded: 'Sản phẩm chế biến', valueAddedDescription: 'Tẩm bột, tẩm ướp và cắt theo yêu cầu', catalog: 'Tải danh mục sản phẩm', catalogCta: 'Tải PDF →' },
  footer: { company: 'Công ty', legalName: 'CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN ĐA QUỐC GIA I.D.I', contact: 'Liên hệ', since: 'Từ năm 2003 · Việt Nam', description: 'CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN ĐA QUỐC GIA I.D.I — doanh nghiệp xuất khẩu cá tra đạt chuẩn ASC đến hơn 50 quốc gia.', headOffice: 'Trụ sở chính', headOfficeAddress: 'Quốc lộ 80, Cụm công nghiệp Vàm Cống, ấp An Thạnh, xã Lấp Vò, Tỉnh Đồng Tháp, Việt Nam', hcmOffice: 'Văn phòng đại diện Hồ Chí Minh', hcmAddress: '9 Nguyễn Kim, phường 12, quận 5, Thành phố Hồ Chí Minh, Việt Nam', phone: 'Điện thoại', hcmPhone: 'Điện thoại văn phòng Hồ Chí Minh', license: 'Số giấy phép kinh doanh: 0303141296 do Sở Kế hoạch và Đầu tư Thành phố Hồ Chí Minh cấp ngày 15/07/2003 · Đại diện: Lê Văn Cảnh' },
  careers: {
    seoTitle: 'Tuyển dụng | IDI Seafood',
    seoDescription: 'Khám phá môi trường làm việc, phúc lợi và gửi CV ứng tuyển để đồng hành cùng IDI Seafood.',
    hero: { imageAlt: 'Đội ngũ IDI tại nhà máy chế biến cá tra', eyebrow: 'Cơ hội nghề nghiệp tại IDI', titleLine1: 'Cùng chúng tôi', titleLine2: 'tạo nên giá trị', description: 'Gia nhập một đội ngũ cùng chung khát vọng phát triển ngành thủy sản Việt Nam bền vững và vươn xa trên thị trường quốc tế.' },
    workplace: { eyebrow: 'Làm việc có ý nghĩa', title: 'Phát triển sự nghiệp trong một hệ sinh thái bền vững', paragraph1: 'Tại IDI, bảo vệ môi trường là một trong những mối quan tâm hàng đầu của chúng tôi vì chúng tôi hiểu rằng việc cải thiện chất lượng môi trường là điều thiết yếu để đạt được mức sống cao hơn cho cộng đồng thân yêu của chúng tôi.', paragraph2: 'Mỗi thành viên đều có cơ hội học hỏi, phát huy năng lực và cùng xây dựng chuỗi giá trị thủy sản có trách nhiệm từ vùng nuôi đến thị trường toàn cầu.', imageAlt: 'Nhân viên IDI trong dây chuyền sản xuất', badge: 'Đồng hành', badgeTitle: 'Cùng phát triển' },
    benefits: {
      eyebrow: 'Lợi ích', title: 'Tại sao bạn nên gia nhập cùng chúng tôi?',
      items: {
        health: { title: 'Bảo hiểm y tế', description: 'Sức khỏe của bạn luôn được quan tâm. Bạn sẽ nhận được bảo hiểm y tế đáp ứng hầu hết các nhu cầu thiết yếu.' },
        reviews: { title: 'Đánh giá thường xuyên', description: 'Đánh giá hiệu suất hai chiều giúp tạo sự cân bằng, ghi nhận đóng góp và đo lường sự phát triển cùng nhau.' },
        locations: { title: 'Vị trí làm việc thuận tiện', description: 'Làm việc tại trụ sở Đồng Tháp hoặc văn phòng đại diện ngay trung tâm Quận 5, Thành phố Hồ Chí Minh.' },
      },
      headOffice: 'Trụ sở chính', headOfficeAddress: 'Quốc lộ 80, Cụm công nghiệp Vàm Cống, ấp An Thạnh, xã Lấp Vò, Tỉnh Đồng Tháp, Việt Nam', representativeOffice: 'Văn phòng đại diện', representativeOfficeAddress: '9 Nguyễn Kim, phường 12, quận 5, Thành phố Hồ Chí Minh', phone: 'Điện thoại', officeDescription: 'Ngay trung tâm Quận 5, thuận tiện tiếp cận nhà hàng, trung tâm chăm sóc sức khỏe, trường học và khu mua sắm.',
    },
    application: { eyebrow: 'Cơ hội nghề nghiệp', title: 'Hãy để chúng tôi biết thêm về bạn', description: 'Đăng CV tại đây để bộ phận tuyển dụng IDI có thể liên hệ khi có vị trí phù hợp với kinh nghiệm và định hướng của bạn.', privacy: 'Hồ sơ được bảo mật', proactive: 'Tiếp nhận ứng tuyển chủ động', response: 'Phản hồi khi có vị trí phù hợp', support: 'Hỗ trợ ứng tuyển', successEyebrow: 'Gửi hồ sơ thành công', successTitle: 'Cảm ơn bạn đã chọn IDI', successDescription: 'Hồ sơ của bạn đã được tiếp nhận. Mã tham chiếu là', closedEyebrow: 'Tạm ngưng nhận hồ sơ', closedTitle: 'Cổng ứng tuyển đang tạm đóng', closedDescription: 'Hiện tại IDI chưa tiếp nhận hồ sơ trực tuyến. Bạn vẫn có thể theo dõi các vị trí đang tuyển và quay lại sau.', formEyebrow: 'Gửi ứng tuyển', formTitle: 'Đăng CV của bạn tại đây', requiredNote: 'Tất cả các trường bên dưới đều là bắt buộc.', positionLabel: 'Vị trí quan tâm', loadingPositions: 'Đang tải vị trí...', openApplication: 'Ứng tuyển tự do', fullName: 'Họ và tên', fullNamePlaceholder: 'Nguyễn Văn A', phone: 'Điện thoại', email: 'Email', address: 'Địa chỉ', addressPlaceholder: 'Tỉnh/Thành phố', cv: 'CV của bạn', fileNote: 'Định dạng DOC, DOCX hoặc PDF; dung lượng nhỏ hơn 10MB.', consent: 'Bằng việc gửi hồ sơ, bạn đồng ý để IDI sử dụng thông tin cho mục đích tuyển dụng.' },
    bottom: { eyebrow: 'Muốn biết thêm về đội ngũ?', title: 'Tìm hiểu thêm về I.D.I' },
    validation: { cvRequired: 'Vui lòng chọn CV của bạn.', cvType: 'CV chỉ chấp nhận định dạng PDF, DOC hoặc DOCX.', cvSize: 'Dung lượng CV không được vượt quá 10MB.', required: 'Thông tin này là bắt buộc.', fullName: 'Họ tên cần có ít nhất 2 ký tự.', phone: 'Vui lòng nhập số điện thoại hợp lệ.', email: 'Vui lòng nhập địa chỉ email hợp lệ.' },
  },
  sustainability: {
    seoTitle: 'Phát triển bền vững | IDI Seafood',
    seoDescription: 'IDI phát triển nuôi trồng thủy sản bền vững, đổi mới chuỗi giá trị và thúc đẩy tài chính xanh vì một tương lai khỏe mạnh.',
    hero: { imageAlt: 'Vùng nuôi trồng thủy sản bền vững của IDI', eyebrow: 'Nuôi dưỡng thiên nhiên', titleLine1: 'Phát triển', titleLine2: 'bền vững', description: 'Vì một tương lai khỏe mạnh, nơi tăng trưởng kinh tế song hành cùng thiên nhiên và cộng đồng.' },
    vision: { eyebrow: 'Tầm nhìn dài hạn', title: 'Nuôi trồng thủy sản bền vững', paragraph1: 'Nuôi trồng thủy sản bền vững là quan tâm đến sự phát triển của các quần thể đang khai thác cũng như bảo tồn hệ sinh thái và một hành tinh lành mạnh. Tại I.D.I, chúng tôi có niềm tin vững chắc rằng, bằng cách nuôi trồng tại vùng đồng bằng sông Cửu Long, chúng tôi có thể sản xuất ra những sản phẩm tốt cho sức khỏe, có giá trị dinh dưỡng và giá thành hợp lý cho toàn xã hội.', paragraph2: 'Cho nên, việc chung sống hòa hợp với môi trường là điều thiết yếu để hiện thực hóa niềm tin đó và tiếp tục chia sẻ những điều tốt đẹp mà thiên nhiên ban tặng cho các thế hệ tương lai.', ecosystems: 'Hệ sinh thái', community: 'Cộng đồng', future: 'Thế hệ tương lai' },
    approach: {
      eyebrow: 'Phương pháp của IDI', title: 'Chúng tôi thực hiện điều đó như thế nào?', action: 'Hành động {{number}}',
      items: {
        listen: { title: 'Chúng tôi lắng nghe', description: 'Chúng tôi quý trọng mọi cơ hội để lắng nghe khách hàng và người tiêu dùng, thấu hiểu các mối quan tâm của họ, xử lý các vấn đề quan trọng và sau đó là thiết lập các ý tưởng mới. Hiểu rõ được mối quan tâm của khách hàng sẽ giúp chúng tôi phát triển chiến lược và đáp ứng tốt hơn nhu cầu của xã hội.' },
        standards: { title: 'Chúng tôi yêu cầu', description: 'I.D.I liên tục tham gia vào các buổi thảo luận với các nhà cung cấp, thông qua giáo dục để học hỏi những phương pháp mới duy trì và nâng cao các kỹ thuật khai thác bền vững. Tiêu chuẩn của chúng tôi được giám sát bởi đội ngũ nhân viên tận tụy, những người thường xuyên đến thăm các nhà cung ứng để đánh giá quá trình hoạt động của họ và đảm bảo rằng họ tuân thủ các quy tắc mà I.D.I đề ra.' },
        innovate: { title: 'Chúng tôi đổi mới', description: 'Chúng tôi tin rằng việc đầu tư vào nghiên cứu và phát triển kiến thức mới sẽ là chìa khóa làm tăng sản lượng nuôi trồng thủy sản một cách bền vững. Tại I.D.I, chúng tôi tận dụng chuỗi giá trị tích hợp toàn diện của mình được hỗ trợ bởi công nghệ mới tiên tiến để cải tiến mọi thứ không ngừng nghỉ.', extra: 'Mục tiêu của I.D.I là toàn quyền kiểm soát trong tất cả các khâu từ sản xuất con giống, thức ăn, chăn nuôi đến thu hoạch và chế biến. Điều này mang lại cho chúng tôi những cơ hội đặc biệt, điều mà khi hoạt động riêng lẻ khó mà đạt được. Chúng tôi thu thập dữ liệu, kinh nghiệm thực tiễn và hoạt động sản xuất từ khắp nơi trên thế giới. Điều này cho phép chúng tôi tái thiết lập với mức độ chính xác cao hơn các đối thủ cạnh tranh và giúp chúng tôi dẫn đầu trong ngành thủy sản.' },
      },
    },
    commitment: { imageAlt: 'Cam kết phát triển nền nông nghiệp bền vững của IDI', eyebrow: 'Cam kết của chúng tôi', title: 'Chúng tôi cam kết phát triển một nền nông nghiệp bền vững' },
    finance: { imageAlt: 'Hoạt động tài chính xanh của IDI', badge: 'Tiên phong', badgeTitle: 'Trái phiếu xanh', eyebrow: 'Tăng trưởng có trách nhiệm', title: 'Tài chính xanh', paragraph1: 'Dưới sự hỗ trợ của GuarantCo, chúng tôi đã phát hành trái phiếu xanh đầu tiên trong ngành nuôi trồng thủy sản tại Châu Á. Theo khuôn khổ trái phiếu xanh của chúng tôi, chúng tôi cam kết phân bổ vốn thu được từ trái phiếu xanh vào các dự án xanh đủ điều kiện, với mục tiêu thúc đẩy việc nuôi trồng và sản xuất cá tra bền vững và thân thiện với môi trường.', paragraph2: 'Các phương pháp chế biến cá bền vững của chúng tôi phù hợp với các tiêu chuẩn bền vững quốc tế được thiết lập bởi Hội đồng Quản lý Nuôi trồng Thủy sản (ASC) và Thực hành Nuôi trồng Thủy sản Tốt nhất (BAP).', paragraph3: 'Những tiêu chuẩn này rất quan trọng đối với các công ty Việt Nam muốn tiếp cận các thị trường có yêu cầu về bền vững khắt khe và đáp ứng nhu cầu ngày càng tăng đối với các sản phẩm thân thiện với môi trường và có nguồn gốc có trách nhiệm.', greenBond: 'Trái phiếu xanh' },
  },
  error: { notFoundTitle: 'Không tìm thấy trang', notFoundMessage: 'Trang bạn yêu cầu không tồn tại hoặc chưa có bản dịch cho ngôn ngữ này.', genericTitle: 'Đã xảy ra lỗi', genericMessage: 'Không thể tải nội dung. Vui lòng thử lại sau.' },
  newsDetail: { copyLink: 'Sao chép liên kết', copied: 'Đã sao chép', copyFailed: 'Không thể sao chép' },
  api: { connectionError: 'Không thể kết nối đến máy chủ. Vui lòng thử lại.' },
}

const en = {
  common: { loading: 'Loading...', retry: 'Try again', viewAll: 'View all', readMore: 'Read more', download: 'Download', search: 'Search', close: 'Close', backHome: 'Back to home', noContent: 'Content is being updated.', minutes: '{{count}} min read' },
  language: { label: 'Language', vi: 'VI', en: 'EN', 'zh-CN': '中文' },
  actions: { all: 'All', viewDetails: 'View details', requestAdvice: 'Request advice', continueProducts: 'Continue browsing products', submitAnotherInquiry: 'Send another inquiry', sending: 'Sending...', submitContact: 'Send inquiry', submitCv: 'Submit your CV', submitAnotherApplication: 'Submit another application', submitApplication: 'Submit application', exploreIdi: 'Explore IDI', exploreProducts: 'Explore products', learnMore: 'Learn more →', viewCatalog: 'View full catalogue →', customProduction: 'Request custom specifications', featuredRead: 'Read featured article', clearFilters: 'Clear filters', allNews: 'View all news', previous: 'Previous', next: 'Next', printArticle: 'Print article', viewMore: 'View more', retryLoad: 'Try loading again' },
  nav: { main: 'Main navigation', footer: 'Footer navigation', openMenu: 'Open menu', closeMenu: 'Close menu', home: 'Home', about: 'About IDI', story: 'Our history', values: 'Core values', products: 'Products', sustainability: 'Sustainability', investors: 'Investors', overview: 'Overview', announcements: 'Announcements', financials: 'Financial reports', annualReports: 'Annual reports', agm: 'General meetings', greenBond: 'Bonds', news: 'News', recipes: 'Recipes', careers: 'Careers', contact: 'Contact', requestQuote: 'Request a quote', investorMenu: 'Investor menu', irContact: 'IR contact' },
  productNav: { fillet: 'Pangasius fillet', filletDescription: 'Skinless, skin-on and multiple trimming specifications', portions: 'Pangasius portions', portionsDescription: 'Portion-cut for food service', whole: 'Whole fish', wholeDescription: 'Butterfly, HGT and cleaned formats', valueAdded: 'Value-added products', valueAddedDescription: 'Breaded, marinated and custom-cut products', catalog: 'Download product catalogue', catalogCta: 'Download PDF →' },
  footer: { company: 'Company', legalName: 'I.D.I INTERNATIONAL DEVELOPMENT & INVESTMENT CORPORATION', contact: 'Contact', since: 'Since 2003 · Vietnam', description: 'I.D.I INTERNATIONAL DEVELOPMENT & INVESTMENT CORPORATION — an ASC-certified pangasius exporter serving more than 50 countries.', headOffice: 'Head office', headOfficeAddress: 'National Road 80, Vam Cong Industrial Cluster, An Thanh Hamlet, Lap Vo Commune, Dong Thap Province, Vietnam', hcmOffice: 'Ho Chi Minh City representative office', hcmAddress: '9 Nguyen Kim Street, Ward 12, District 5, Ho Chi Minh City, Vietnam', phone: 'Phone', hcmPhone: 'Ho Chi Minh City office phone', license: 'Business registration no. 0303141296 issued by the Ho Chi Minh City Department of Planning and Investment on 15/07/2003 · Representative: Le Van Canh' },
  careers: {
    seoTitle: 'Careers | IDI Seafood',
    seoDescription: 'Explore our workplace, employee benefits, and submit your CV to build your career with IDI Seafood.',
    hero: { imageAlt: 'The IDI team at the pangasius processing plant', eyebrow: 'Career opportunities at IDI', titleLine1: 'Together, we', titleLine2: 'create lasting value', description: 'Join a team united by the ambition to develop Vietnam’s seafood industry sustainably and expand its reach in global markets.' },
    workplace: { eyebrow: 'Meaningful work', title: 'Grow your career in a sustainable ecosystem', paragraph1: 'At IDI, protecting the environment is one of our highest priorities. We believe improving environmental quality is essential to creating a better standard of living for the communities we care about.', paragraph2: 'Every team member has opportunities to learn, develop their strengths, and help build a responsible seafood value chain from farm to global markets.', imageAlt: 'IDI employees on the production line', badge: 'Together', badgeTitle: 'Growing as one' },
    benefits: {
      eyebrow: 'Benefits', title: 'Why should you join us?',
      items: {
        health: { title: 'Health insurance', description: 'Your well-being matters. Our health insurance coverage supports most essential healthcare needs.' },
        reviews: { title: 'Regular reviews', description: 'Two-way performance reviews create balance, recognize contributions, and help us measure progress together.' },
        locations: { title: 'Convenient workplaces', description: 'Work at our Dong Thap headquarters or our representative office in the heart of District 5, Ho Chi Minh City.' },
      },
      headOffice: 'Head office', headOfficeAddress: 'National Road 80, Vam Cong Industrial Cluster, An Thanh Hamlet, Lap Vo Commune, Dong Thap Province, Vietnam', representativeOffice: 'Representative office', representativeOfficeAddress: '9 Nguyen Kim Street, Ward 12, District 5, Ho Chi Minh City', phone: 'Phone', officeDescription: 'Located in central District 5 with convenient access to restaurants, healthcare facilities, schools, and shopping areas.',
    },
    application: { eyebrow: 'Career opportunities', title: 'Tell us more about yourself', description: 'Upload your CV so the IDI recruitment team can contact you when a role matches your experience and career goals.', privacy: 'Your application is confidential', proactive: 'Open applications are welcome', response: 'We respond when a suitable role opens', support: 'Application support', successEyebrow: 'Application submitted', successTitle: 'Thank you for choosing IDI', successDescription: 'We have received your application. Your reference number is', closedEyebrow: 'Applications paused', closedTitle: 'The application portal is temporarily closed', closedDescription: 'IDI is not accepting online applications at this time. You can still follow our current openings and return later.', formEyebrow: 'Apply now', formTitle: 'Upload your CV here', requiredNote: 'All fields below are required.', positionLabel: 'Position of interest', loadingPositions: 'Loading positions...', openApplication: 'General application', fullName: 'Full name', fullNamePlaceholder: 'Your full name', phone: 'Phone', email: 'Email', address: 'Address', addressPlaceholder: 'Province/City', cv: 'Your CV', fileNote: 'DOC, DOCX, or PDF format; maximum file size 10MB.', consent: 'By submitting your application, you agree that IDI may use your information for recruitment purposes.' },
    bottom: { eyebrow: 'Want to learn more about our team?', title: 'Discover more about I.D.I' },
    validation: { cvRequired: 'Please select your CV.', cvType: 'Your CV must be a PDF, DOC, or DOCX file.', cvSize: 'Your CV must not exceed 10MB.', required: 'This field is required.', fullName: 'Your full name must contain at least 2 characters.', phone: 'Please enter a valid phone number.', email: 'Please enter a valid email address.' },
  },
  sustainability: {
    seoTitle: 'Sustainability | IDI Seafood',
    seoDescription: 'IDI advances sustainable aquaculture, value-chain innovation, and green finance for a healthier future.',
    hero: { imageAlt: 'IDI sustainable aquaculture area', eyebrow: 'Nurturing nature', titleLine1: 'Sustainable', titleLine2: 'development', description: 'For a healthier future where economic growth advances in harmony with nature and communities.' },
    vision: { eyebrow: 'A long-term vision', title: 'Sustainable aquaculture', paragraph1: 'Sustainable aquaculture means supporting the development of farmed populations while preserving ecosystems and a healthy planet. At I.D.I, we firmly believe that farming in the Mekong Delta enables us to provide healthy, nutritious, and affordable products for society.', paragraph2: 'Living in harmony with the environment is therefore essential to realizing this belief and preserving nature’s benefits for future generations.', ecosystems: 'Ecosystems', community: 'Communities', future: 'Future generations' },
    approach: {
      eyebrow: 'The IDI approach', title: 'How do we put it into practice?', action: 'Action {{number}}',
      items: {
        listen: { title: 'We listen', description: 'We value every opportunity to listen to customers and consumers, understand their concerns, address important issues, and develop new ideas. A clear understanding of customer priorities helps us shape our strategy and respond better to society’s needs.' },
        standards: { title: 'We set high standards', description: 'I.D.I maintains an ongoing dialogue with suppliers and uses education to discover new ways to sustain and improve responsible production practices. Our dedicated team regularly visits suppliers, reviews their operations, and ensures compliance with the standards established by I.D.I.' },
        innovate: { title: 'We innovate', description: 'We believe that investing in research and developing new knowledge is key to increasing aquaculture output sustainably. At I.D.I, we combine our fully integrated value chain with advanced technologies to drive continuous improvement.', extra: 'I.D.I aims to maintain full control across every stage, from fingerling and feed production to farming, harvesting, and processing. This integration creates opportunities that are difficult to achieve in isolation. By gathering data, practical experience, and production insight from around the world, we can refine our operations with greater precision and remain at the forefront of the seafood industry.' },
      },
    },
    commitment: { imageAlt: 'IDI commitment to sustainable agriculture', eyebrow: 'Our commitment', title: 'We are committed to developing sustainable agriculture' },
    finance: { imageAlt: 'IDI green finance activities', badge: 'Pioneering', badgeTitle: 'Green bond', eyebrow: 'Responsible growth', title: 'Green finance', paragraph1: 'Backed by GuarantCo, we issued the first green bond in Asia’s aquaculture sector. Under our green bond framework, we are committed to allocating the proceeds to eligible green projects that promote sustainable and environmentally responsible pangasius farming and production.', paragraph2: 'Our sustainable fish-processing practices align with international sustainability standards established by the Aquaculture Stewardship Council (ASC) and Best Aquaculture Practices (BAP).', paragraph3: 'These standards are essential for Vietnamese companies seeking access to markets with stringent sustainability requirements and responding to growing demand for environmentally friendly, responsibly sourced products.', greenBond: 'Green Bond' },
  },
  error: { notFoundTitle: 'Page not found', notFoundMessage: 'The requested page does not exist or is not translated into this language.', genericTitle: 'Something went wrong', genericMessage: 'The content could not be loaded. Please try again later.' },
  newsDetail: { copyLink: 'Copy link', copied: 'Copied', copyFailed: 'Unable to copy' },
  api: { connectionError: 'Could not connect to the server. Please try again.' },
}

const zhCN = {
  common: { loading: '加载中...', retry: '重试', viewAll: '查看全部', readMore: '阅读更多', download: '下载', search: '搜索', close: '关闭', backHome: '返回首页', noContent: '内容正在更新中。', minutes: '阅读 {{count}} 分钟' },
  language: { label: '语言', vi: 'VI', en: 'EN', 'zh-CN': '中文' },
  actions: { all: '全部', viewDetails: '查看详情', requestAdvice: '咨询产品', continueProducts: '继续浏览产品', submitAnotherInquiry: '发送其他咨询', sending: '发送中...', submitContact: '发送联系信息', submitCv: '提交简历', submitAnotherApplication: '提交另一份申请', submitApplication: '提交申请', exploreIdi: '探索 IDI', exploreProducts: '探索产品', learnMore: '了解更多 →', viewCatalog: '查看完整目录 →', customProduction: '咨询定制规格', featuredRead: '阅读精选文章', clearFilters: '清除筛选', allNews: '查看所有新闻', previous: '上一页', next: '下一页', printArticle: '打印文章', viewMore: '查看更多', retryLoad: '重新加载' },
  nav: { main: '主导航', footer: '页脚导航', openMenu: '打开菜单', closeMenu: '关闭菜单', home: '首页', about: '关于 IDI', story: '发展历程', values: '核心价值观', products: '产品', sustainability: '可持续发展', investors: '投资者', overview: '概览', announcements: '公告', financials: '财务报告', annualReports: '年度报告', agm: '股东大会', greenBond: '债券', news: '新闻', recipes: '食谱', careers: '招聘', contact: '联系我们', requestQuote: '询价', investorMenu: '投资者目录', irContact: '投资者关系联系' },
  productNav: { fillet: '巴沙鱼片', filletDescription: '去皮、带皮及多种修整规格', portions: '巴沙鱼段', portionsDescription: '餐饮服务定制分切', whole: '整鱼', wholeDescription: '蝴蝶切、去头去内脏及清理规格', valueAdded: '深加工产品', valueAddedDescription: '裹粉、腌制及定制切割产品', catalog: '下载产品目录', catalogCta: '下载 PDF →' },
  footer: { company: '公司', legalName: 'I.D.I 国际发展投资股份公司', contact: '联系我们', since: '始于 2003 · 越南', description: 'I.D.I 国际发展投资股份公司——向全球 50 多个国家出口 ASC 认证巴沙鱼产品。', headOffice: '总部', headOfficeAddress: '越南同塔省垃圩社安盛邑汪贡工业区80号国道', hcmOffice: '胡志明市代表处', hcmAddress: '越南胡志明市第五郡第十二坊阮金街9号', phone: '电话', hcmPhone: '胡志明市办公室电话', license: '营业执照号：0303141296，由胡志明市计划投资厅于 2003 年 7 月 15 日签发 · 法定代表人：Le Van Canh' },
  careers: {
    seoTitle: '人才招聘 | IDI Seafood',
    seoDescription: '了解 IDI Seafood 的工作环境与员工福利，并提交简历，与我们携手发展。',
    hero: { imageAlt: 'IDI 团队在巴沙鱼加工厂工作', eyebrow: 'IDI 职业机会', titleLine1: '与我们携手', titleLine2: '共创长远价值', description: '加入志同道合的团队，共同推动越南水产业可持续发展，迈向更广阔的国际市场。' },
    workplace: { eyebrow: '让工作更有意义', title: '在可持续发展的生态体系中成就职业未来', paragraph1: '在 IDI，环境保护始终是我们的首要关注之一。我们深知，改善环境质量是提升社区生活品质的重要基础。', paragraph2: '每位成员都有机会持续学习、发挥专长，并共同建设从养殖基地到全球市场的负责任水产品价值链。', imageAlt: 'IDI 员工在生产线上工作', badge: '携手同行', badgeTitle: '共同成长' },
    benefits: {
      eyebrow: '员工福利', title: '为什么选择加入我们？',
      items: {
        health: { title: '医疗保险', description: '我们始终关心您的健康，并提供覆盖大多数基本医疗需求的保险保障。' },
        reviews: { title: '定期评估', description: '双向绩效评估有助于保持平衡、认可贡献，并共同衡量成长与进步。' },
        locations: { title: '便利的工作地点', description: '您可在同塔省总部或位于胡志明市第五郡中心的代表处工作。' },
      },
      headOffice: '总部', headOfficeAddress: '越南同塔省垃圩社安盛邑汪贡工业区80号国道', representativeOffice: '代表处', representativeOfficeAddress: '越南胡志明市第五郡第十二坊阮金街9号', phone: '电话', officeDescription: '办公室位于第五郡中心，前往餐厅、医疗机构、学校和购物区都十分便利。',
    },
    application: { eyebrow: '职业机会', title: '让我们进一步了解您', description: '请在此上传简历。当有符合您经验与职业方向的职位时，IDI 招聘团队将与您联系。', privacy: '申请资料严格保密', proactive: '欢迎主动投递', response: '有合适职位时及时联系', support: '应聘支持', successEyebrow: '申请提交成功', successTitle: '感谢您选择 IDI', successDescription: '我们已收到您的申请。您的申请编号是', closedEyebrow: '暂停接收申请', closedTitle: '在线申请通道暂时关闭', closedDescription: 'IDI 目前暂不接收在线申请。您仍可关注最新招聘职位，稍后再来申请。', formEyebrow: '提交申请', formTitle: '在此上传您的简历', requiredNote: '以下所有字段均为必填项。', positionLabel: '意向职位', loadingPositions: '正在加载职位...', openApplication: '主动申请', fullName: '姓名', fullNamePlaceholder: '请输入姓名', phone: '电话', email: '电子邮箱', address: '地址', addressPlaceholder: '省／城市', cv: '您的简历', fileNote: '支持 DOC、DOCX 或 PDF 格式；文件大小不得超过 10MB。', consent: '提交申请即表示您同意 IDI 将您的信息用于招聘目的。' },
    bottom: { eyebrow: '想进一步了解我们的团队？', title: '深入了解 I.D.I' },
    validation: { cvRequired: '请选择您的简历。', cvType: '简历仅支持 PDF、DOC 或 DOCX 格式。', cvSize: '简历文件不得超过 10MB。', required: '此项为必填项。', fullName: '姓名至少需要 2 个字符。', phone: '请输入有效的电话号码。', email: '请输入有效的电子邮箱地址。' },
  },
  sustainability: {
    seoTitle: '可持续发展 | IDI Seafood',
    seoDescription: 'IDI 推动可持续水产养殖、价值链创新与绿色金融，共创更健康的未来。',
    hero: { imageAlt: 'IDI 可持续水产养殖区', eyebrow: '滋养自然', titleLine1: '可持续', titleLine2: '发展', description: '共创健康未来，让经济增长与自然环境和社区发展和谐并进。' },
    vision: { eyebrow: '长远愿景', title: '可持续水产养殖', paragraph1: '可持续水产养殖不仅关注养殖种群的发展，也重视生态系统保护与地球健康。I.D.I 坚信，依托湄公河三角洲开展养殖，我们能够为社会提供健康、营养且价格合理的产品。', paragraph2: '因此，与环境和谐共生是实现这一信念的关键，也能让大自然的馈赠延续至未来世代。', ecosystems: '生态系统', community: '社区', future: '未来世代' },
    approach: {
      eyebrow: 'IDI 的实践方式', title: '我们如何将理念付诸实践？', action: '行动 {{number}}',
      items: {
        listen: { title: '我们倾听', description: '我们珍视每一次倾听客户和消费者声音的机会，深入了解他们的关切，处理重要问题，并由此孕育新的构想。充分理解客户关注的重点，有助于我们完善战略，更好地回应社会需求。' },
        standards: { title: '我们坚持高标准', description: 'I.D.I 持续与供应商展开交流，并通过培训学习维护和改进可持续生产的新方法。我们的专业团队会定期走访供应商，评估其运营流程，确保他们遵守 I.D.I 制定的各项标准。' },
        innovate: { title: '我们持续创新', description: '我们相信，投资研究并发展新知识，是可持续提高水产养殖产量的关键。I.D.I 将完整的一体化价值链与先进技术相结合，不断推动各环节改进。', extra: 'I.D.I 致力于全面掌控从鱼苗、饲料、养殖到捕捞和加工的每一个环节。一体化运营为我们创造了单独作业难以获得的独特机会。通过汇集全球数据、实践经验和生产洞察，我们能够更精准地优化运营，并保持在水产业的领先地位。' },
      },
    },
    commitment: { imageAlt: 'IDI 对可持续农业发展的承诺', eyebrow: '我们的承诺', title: '我们致力于推动可持续农业发展' },
    finance: { imageAlt: 'IDI 绿色金融活动', badge: '行业先锋', badgeTitle: '绿色债券', eyebrow: '负责任的增长', title: '绿色金融', paragraph1: '在 GuarantCo 的支持下，我们发行了亚洲水产养殖领域首只绿色债券。根据绿色债券框架，我们承诺将募集资金投入符合条件的绿色项目，推动巴沙鱼养殖与生产朝着可持续、环境友好的方向发展。', paragraph2: '我们的可持续鱼类加工实践符合水产养殖管理委员会（ASC）和最佳水产养殖规范（BAP）制定的国际可持续发展标准。', paragraph3: '这些标准对于希望进入可持续性要求严格市场的越南企业至关重要，也有助于满足市场对环保、负责任来源产品日益增长的需求。', greenBond: '绿色债券' },
  },
  error: { notFoundTitle: '找不到页面', notFoundMessage: '您请求的页面不存在，或尚未提供此语言版本。', genericTitle: '发生错误', genericMessage: '无法加载内容，请稍后重试。' },
  newsDetail: { copyLink: '复制链接', copied: '已复制', copyFailed: '无法复制' },
  api: { connectionError: '无法连接服务器，请重试。' },
}

export const TRANSLATIONS = Object.freeze({ vi, en, 'zh-CN': zhCN })
