const vi = {
  common: { loading: 'Đang tải...', retry: 'Thử lại', viewAll: 'Xem tất cả', readMore: 'Đọc thêm', download: 'Tải xuống', search: 'Tìm kiếm', close: 'Đóng', backHome: 'Về trang chủ', noContent: 'Nội dung đang được cập nhật.', minutes: '{{count}} phút' },
  language: { label: 'Ngôn ngữ', vi: 'VI', en: 'EN', 'zh-CN': '中文' },
  actions: { all: 'Tất cả', viewDetails: 'Xem chi tiết', requestAdvice: 'Yêu cầu tư vấn', continueProducts: 'Tiếp tục xem sản phẩm', submitAnotherInquiry: 'Gửi yêu cầu khác', sending: 'Đang gửi...', submitContact: 'Gửi liên hệ', submitCv: 'Gửi CV ứng tuyển', submitAnotherApplication: 'Gửi hồ sơ khác', submitApplication: 'Gửi ứng tuyển', exploreIdi: 'Khám phá IDI', exploreProducts: 'Khám phá sản phẩm', learnMore: 'Tìm hiểu thêm →', viewCatalog: 'Xem toàn bộ danh mục →', customProduction: 'Nhận sản xuất theo quy cách riêng', featuredRead: 'Đọc bài nổi bật', clearFilters: 'Xóa bộ lọc', allNews: 'Xem tất cả tin tức', previous: 'Trước', next: 'Sau', printArticle: 'In bài viết', viewMore: 'Xem thêm', retryLoad: 'Thử tải lại' },
  nav: { main: 'Điều hướng chính', footer: 'Điều hướng cuối trang', openMenu: 'Mở menu', closeMenu: 'Đóng menu', home: 'Trang chủ', about: 'Về IDI', story: 'Lịch sử phát triển', values: 'Giá trị cốt lõi', products: 'Sản phẩm', sustainability: 'Phát triển bền vững', investors: 'Nhà đầu tư', overview: 'Tổng quan', announcements: 'Thông báo', financials: 'Báo cáo tài chính', annualReports: 'Báo cáo thường niên', agm: 'Đại hội cổ đông', greenBond: 'Trái phiếu', news: 'Tin tức', recipes: 'Món ăn', careers: 'Tuyển dụng', contact: 'Liên hệ', requestQuote: 'Yêu cầu báo giá', investorMenu: 'Danh mục nhà đầu tư', irContact: 'Liên hệ IR' },
  productNav: { fillet: 'Cá tra phi lê', filletDescription: 'Không da, có da và nhiều quy cách chỉnh hình', portions: 'Cá tra cắt khúc', portionsDescription: 'Cắt theo khẩu phần cho dịch vụ thực phẩm', whole: 'Cá nguyên con', wholeDescription: 'Dạng bướm, HGT và làm sạch', valueAdded: 'Sản phẩm chế biến', valueAddedDescription: 'Tẩm bột, tẩm ướp và cắt theo yêu cầu', catalog: 'Tải danh mục sản phẩm', catalogCta: 'Tải PDF →' },
  footer: { company: 'Công ty', contact: 'Liên hệ', since: 'Từ năm 2003 · Việt Nam', description: 'Công ty Cổ phần Đầu tư và Phát triển Đa Quốc Gia I.D.I — doanh nghiệp xuất khẩu cá tra đạt chuẩn ASC đến hơn 50 quốc gia.', headOffice: 'Trụ sở chính', headOfficeAddress: 'Quốc lộ 80, Cụm công nghiệp Vàm Cống, ấp An Thạnh, xã Lấp Vò, Tỉnh Đồng Tháp, Việt Nam', hcmOffice: 'Văn phòng đại diện Hồ Chí Minh', hcmAddress: '9 Nguyễn Kim, phường 12, quận 5, Thành phố Hồ Chí Minh, Việt Nam', phone: 'Điện thoại', hcmPhone: 'Điện thoại văn phòng Hồ Chí Minh', license: 'Số giấy phép kinh doanh: 0303141296 do Sở Kế hoạch và Đầu tư Thành phố Hồ Chí Minh cấp ngày 15/07/2003 · Đại diện: Lê Văn Cảnh' },
  error: { notFoundTitle: 'Không tìm thấy trang', notFoundMessage: 'Trang bạn yêu cầu không tồn tại hoặc chưa có bản dịch cho ngôn ngữ này.', genericTitle: 'Đã xảy ra lỗi', genericMessage: 'Không thể tải nội dung. Vui lòng thử lại sau.' },
  newsDetail: { copyLink: 'Sao chép liên kết', copied: 'Đã sao chép', copyFailed: 'Không thể sao chép' },
  api: { connectionError: 'Không thể kết nối đến máy chủ. Vui lòng thử lại.' },
}

const en = {
  common: { loading: 'Loading...', retry: 'Try again', viewAll: 'View all', readMore: 'Read more', download: 'Download', search: 'Search', close: 'Close', backHome: 'Back to home', noContent: 'Content is being updated.', minutes: '{{count}} min read' },
  language: { label: 'Language', vi: 'VI', en: 'EN', 'zh-CN': '中文' },
  actions: { all: 'All', viewDetails: 'View details', requestAdvice: 'Request advice', continueProducts: 'Continue browsing products', submitAnotherInquiry: 'Send another inquiry', sending: 'Sending...', submitContact: 'Send inquiry', submitCv: 'Submit your CV', submitAnotherApplication: 'Submit another application', submitApplication: 'Submit application', exploreIdi: 'Explore IDI', exploreProducts: 'Explore products', learnMore: 'Learn more →', viewCatalog: 'View full catalogue →', customProduction: 'Request custom specifications', featuredRead: 'Read featured article', clearFilters: 'Clear filters', allNews: 'View all news', previous: 'Previous', next: 'Next', printArticle: 'Print article', viewMore: 'View more', retryLoad: 'Try loading again' },
  nav: { main: 'Main navigation', footer: 'Footer navigation', openMenu: 'Open menu', closeMenu: 'Close menu', home: 'Home', about: 'About IDI', story: 'Our history', values: 'Core values', products: 'Products', sustainability: 'Sustainability', investors: 'Investors', overview: 'Overview', announcements: 'Announcements', financials: 'Financial reports', annualReports: 'Annual reports', agm: 'General meetings', greenBond: 'Bonds', news: 'News', recipes: 'Recipes', careers: 'Careers', contact: 'Contact', requestQuote: 'Request a quote', investorMenu: 'Investor menu', irContact: 'IR contact' },
  productNav: { fillet: 'Pangasius fillet', filletDescription: 'Skinless, skin-on and multiple trimming specifications', portions: 'Pangasius portions', portionsDescription: 'Portion-cut for food service', whole: 'Whole fish', wholeDescription: 'Butterfly, HGT and cleaned formats', valueAdded: 'Value-added products', valueAddedDescription: 'Breaded, marinated and custom-cut products', catalog: 'Download product catalogue', catalogCta: 'Download PDF →' },
  footer: { company: 'Company', contact: 'Contact', since: 'Since 2003 · Vietnam', description: 'I.D.I International Development & Investment Corporation — an ASC-certified pangasius exporter serving more than 50 countries.', headOffice: 'Head office', headOfficeAddress: 'National Road 80, Vam Cong Industrial Cluster, An Thanh Hamlet, Lap Vo Commune, Dong Thap Province, Vietnam', hcmOffice: 'Ho Chi Minh City representative office', hcmAddress: '9 Nguyen Kim Street, Ward 12, District 5, Ho Chi Minh City, Vietnam', phone: 'Phone', hcmPhone: 'Ho Chi Minh City office phone', license: 'Business registration no. 0303141296 issued by the Ho Chi Minh City Department of Planning and Investment on 15/07/2003 · Representative: Le Van Canh' },
  error: { notFoundTitle: 'Page not found', notFoundMessage: 'The requested page does not exist or is not translated into this language.', genericTitle: 'Something went wrong', genericMessage: 'The content could not be loaded. Please try again later.' },
  newsDetail: { copyLink: 'Copy link', copied: 'Copied', copyFailed: 'Unable to copy' },
  api: { connectionError: 'Could not connect to the server. Please try again.' },
}

const zhCN = {
  common: { loading: '加载中...', retry: '重试', viewAll: '查看全部', readMore: '阅读更多', download: '下载', search: '搜索', close: '关闭', backHome: '返回首页', noContent: '内容正在更新中。', minutes: '阅读 {{count}} 分钟' },
  language: { label: '语言', vi: 'VI', en: 'EN', 'zh-CN': '中文' },
  actions: { all: '全部', viewDetails: '查看详情', requestAdvice: '咨询产品', continueProducts: '继续浏览产品', submitAnotherInquiry: '发送其他咨询', sending: '发送中...', submitContact: '发送联系信息', submitCv: '提交简历', submitAnotherApplication: '提交另一份申请', submitApplication: '提交申请', exploreIdi: '探索 IDI', exploreProducts: '探索产品', learnMore: '了解更多 →', viewCatalog: '查看完整目录 →', customProduction: '咨询定制规格', featuredRead: '阅读精选文章', clearFilters: '清除筛选', allNews: '查看所有新闻', previous: '上一页', next: '下一页', printArticle: '打印文章', viewMore: '查看更多', retryLoad: '重新加载' },
  nav: { main: '主导航', footer: '页脚导航', openMenu: '打开菜单', closeMenu: '关闭菜单', home: '首页', about: '关于 IDI', story: '发展历程', values: '核心价值观', products: '产品', sustainability: '可持续发展', investors: '投资者', overview: '概览', announcements: '公告', financials: '财务报告', annualReports: '年度报告', agm: '股东大会', greenBond: '债券', news: '新闻', recipes: '食谱', careers: '招聘', contact: '联系我们', requestQuote: '询价', investorMenu: '投资者目录', irContact: '投资者关系联系' },
  productNav: { fillet: '巴沙鱼片', filletDescription: '去皮、带皮及多种修整规格', portions: '巴沙鱼段', portionsDescription: '餐饮服务定制分切', whole: '整鱼', wholeDescription: '蝴蝶切、去头去内脏及清理规格', valueAdded: '深加工产品', valueAddedDescription: '裹粉、腌制及定制切割产品', catalog: '下载产品目录', catalogCta: '下载 PDF →' },
  footer: { company: '公司', contact: '联系我们', since: '始于 2003 · 越南', description: 'I.D.I 国际发展投资股份公司——向全球 50 多个国家出口 ASC 认证巴沙鱼产品。', headOffice: '总部', headOfficeAddress: '越南同塔省垃圩社安盛邑汪贡工业区80号国道', hcmOffice: '胡志明市代表处', hcmAddress: '越南胡志明市第五郡第十二坊阮金街9号', phone: '电话', hcmPhone: '胡志明市办公室电话', license: '营业执照号：0303141296，由胡志明市计划投资厅于 2003 年 7 月 15 日签发 · 法定代表人：Lê Văn Cảnh' },
  error: { notFoundTitle: '找不到页面', notFoundMessage: '您请求的页面不存在，或尚未提供此语言版本。', genericTitle: '发生错误', genericMessage: '无法加载内容，请稍后重试。' },
  newsDetail: { copyLink: '复制链接', copied: '已复制', copyFailed: '无法复制' },
  api: { connectionError: '无法连接服务器，请重试。' },
}

export const TRANSLATIONS = Object.freeze({ vi, en, 'zh-CN': zhCN })
